# LightDM Configuration - Kyxgo OS

[LightDM]
start-default-seat=true
log-directory=/var/log/lightdm
run-directory=/var/run/lightdm
cache-directory=/var/cache/lightdm
sessions-directory=/usr/share/lightdm/sessions:/usr/share/xsessions:/usr/share/wayland-sessions

[Seat:*]
greeter-session=lightdm-gtk-greeter
greeter-hide-users=false
greeter-allow-guest=false
user-session=xfce
allow-user-switching=true
session-wrapper=/etc/X11/Xsession

[XDMCPServer]
enabled=false

[VNCServer]
enabled=false
