# LightDM GTK Configuration - Kyxgo OS
# Available configuration options listed below.

[greeter]
background = /usr/share/images/desktop-base/default
user-background = false
theme-name = Yaru-blue-dark
icon-theme-name = Papirus
cursor-theme-name = Yaru
font-name = Roboto 10
xft-antialias = true
xft-hintstyle = hintfull
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~language;~layout;~session;~a11y;~power
clock-format = %H:%M - %a %d %b
show-clock = true
screensaver-timeout = 300
