#!/bin/sh
# live-build configuration script
# see 'man lb config'

lb config noauto \
--apt-recommends false \
--apt-indices false \
--architectures amd64 \
--archive-areas "main contrib non-free non-free-firmware" \
--backports true \
--security true \
--source false \
--binary-filesystem ext4 \
--binary-images iso-hybrid \
--checksums sha256 \
--clean \
--debconf-frontend noninteractive \
--debian-installer live \
--debian-installer-distribution bookworm \
--debian-installer-gui true \
--debootstrap debootstrap \
--distribution bookworm \
--firmware-binary true \
--firmware-chroot true \
--initramfs live-boot \
--initsystem systemd \
--iso-publisher "kyxgo-live-config" \
--iso-volume "kyxgo-live-config-5.0.0" \
--linux-packages "linux-image-amd64" \
--bootappend-live "boot=live config splash" \
--mirror-bootstrap "http://deb.debian.org/debian/" \
--mirror-chroot "http://deb.debian.org/debian/" \
--mirror-binary "http://deb.debian.org/debian/" \
--memtest memtest86+

"${@}"
